site_name: Nusantara Mall API Docs
pages:
    - Home: index.md
    - Authentication: authentification.md
    - Users: users.md
    - Categories: categories.md
    - Brands: brands.md
    - Products: products.md
    - About: about.md
theme: readthedocs
